[versions]
loom = "1.8-SNAPSHOT"
minecraft = "1.20.1"
yarn = "1.20.1+build.10"
fabric-loader = "0.16.9"
mixinsquared = "0.2.0"

sereneseasons = "4RgDk9NB"

[libraries]
com-mojang-minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
net-fabricmc-yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
net-fabricmc-fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
com-github-bawnorton-mixinsquared-fabric = { module = "com.github.bawnorton.mixinsquared:mixinsquared-fabric", version.ref = "mixinsquared" }

modrinth-sereneseasons = { module = "maven.modrinth:serene-seasons", version.ref = "sereneseasons" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }